export const localization = {
  ua: {
    countries: {
      Afghanistan: "Афганістан",
      Albania: "Албанія",
      Algeria: "Алжир",
      "American Samoa": "Американське Самоа",
      Andorra: "Андорра",
      Angola: "Ангола",
      Anguilla: "Ангілья",
      Antarctica: "Антарктида",
      "Antigua and Barbuda": "Антигуа і Барбуда",
      Argentina: "Аргентина",
      Armenia: "Вірменія",
      Aruba: "Аруба",
      Australia: "Австралія",
      Austria: "Австрія",
      Azerbaijan: "Азербайджан",
      Bahamas: "Багамські Острови",
      Bahrain: "Бахрейн",
      Bangladesh: "Бангладеш",
      Barbados: "Барбадос",
      Belarus: "Білорусь",
      Belgium: "Бельгія",
      Belize: "Беліз",
      Benin: "Бенін",
      Bermuda: "Бермуди",
      Bhutan: "Бутан",
      Bolivia: "Болівія",
      "Bosnia and Herzegovina": "Боснія і Герцеговина",
      Botswana: "Ботсвана",
      "Bouvet Island": "Острів Буве",
      Brazil: "Бразилія",
      "British Indian Ocean Territory":
        "Британська Територія в Індійському Океані",
      "British Virgin Islands": "Британські Віргінські Острови",
      Brunei: "Бруней",
      Bulgaria: "Болгарія",
      "Burkina Faso": "Буркіна-Фасо",
      Burundi: "Бурунді",
      Cambodia: "Камбоджа",
      Cameroon: "Камерун",
      Canada: "Канада",
      "Cape Verde": "Кабо-Верде",
      "Caribbean Netherlands": "Карибські Нідерланди",
      "Cayman Islands": "Кайманові Острови",
      "Central African Republic": "Центральноафриканська Республіка",
      Chad: "Чад",
      Chile: "Чилі",
      China: "Китайська Народна Республіка",
      "Christmas Island": "Острів Різдва",
      "Cocos (Keeling) Islands": "Кокосові Острови",
      Colombia: "Колумбія",
      Comoros: "Коморські Острови",
      "Cook Islands": "Острови Кука",
      "Costa Rica": "Коста-Рика",
      Croatia: "Хорватія",
      Cuba: "Куба",
      Curaçao: "Кюрасао",
      Cyprus: "Кіпр",
      Czechia: "Чехія",
      "DR Congo": "ДР Конго",
      Denmark: "Данія",
      Djibouti: "Джибуті",
      Dominica: "Домініка",
      "Dominican Republic": "Домініканська Республіка",
      Ecuador: "Еквадор",
      Egypt: "Єгипет",
      "El Salvador": "Сальвадор",
      "Equatorial Guinea": "Екваторіальна Гвінея",
      Eritrea: "Еритрея",
      Estonia: "Естонія",
      Eswatini: "Есватіні",
      Ethiopia: "Ефіопія",
      "Falkland Islands": "Фолклендські Острови",
      "Faroe Islands": "Фарерські острови",
      Fiji: "Фіджі",
      Finland: "Фінляндія",
      France: "Франція",
      "French Guiana": "Французька Гвіана",
      "French Polynesia": "Французька Полінезія",
      "French Southern and Antarctic Lands":
        "Французькі Південні і Антарктичні Території",
      Gabon: "Габон",
      Gambia: "Гамбія",
      Georgia: "Грузія",
      Germany: "Німеччина",
      Ghana: "Гана",
      Gibraltar: "Гібралтар",
      Greece: "Греція",
      Greenland: "Гренландія",
      Grenada: "Гренада",
      Guadeloupe: "Гваделупа",
      Guam: "Гуам",
      Guatemala: "Гватемала",
      Guernsey: "Гернсі",
      Guinea: "Гвінея",
      "Guinea-Bissau": "Гвінея-Бісау",
      Guyana: "Гаяна",
      Haiti: "Гаїті",
      "Heard Island and McDonald Islands": "Острів Герд і острови Макдональд",
      Honduras: "Гондурас",
      "Hong Kong": "Гонконг",
      Hungary: "Угорщина",
      Iceland: "Ісландія",
      India: "Індія",
      Indonesia: "Індонезія",
      Iran: "Іран",
      Iraq: "Ірак",
      Ireland: "Ірландія",
      "Isle of Man": "Острів Мен",
      Israel: "Ізраїль",
      Italy: "Італія",
      "Ivory Coast": "Кот-д'Івуар",
      Jamaica: "Ямайка",
      Japan: "Японія",
      Jersey: "Джерсі",
      Jordan: "Йорданія",
      Kazakhstan: "Казахстан",
      Kenya: "Кенія",
      Kiribati: "Кірибаті",
      Kosovo: "Косово",
      Kuwait: "Кувейт",
      Kyrgyzstan: "Киргизстан",
      Laos: "Лаос",
      Latvia: "Латвія",
      Lebanon: "Ліван",
      Lesotho: "Лесото",
      Liberia: "Ліберія",
      Libya: "Лівія",
      Liechtenstein: "Ліхтенштейн",
      Lithuania: "Литва",
      Luxembourg: "Люксембург",
      Macau: "Макао",
      Madagascar: "Мадагаскар",
      Malawi: "Малаві",
      Malaysia: "Малайзія",
      Maldives: "Мальдіви",
      Mali: "Малі",
      Malta: "Мальта",
      "Marshall Islands": "Маршаллові Острови",
      Martinique: "Мартиніка",
      Mauritania: "Мавританія",
      Mauritius: "Маврикій",
      Mayotte: "Майотта",
      Mexico: "Мексика",
      Micronesia: "Федеративні Штати Мікронезії",
      Moldova: "Молдова",
      Monaco: "Монако",
      Mongolia: "Монголія",
      Montenegro: "Чорногорія",
      Montserrat: "Монтсеррат",
      Morocco: "Марокко",
      Mozambique: "Мозамбік",
      Myanmar: "М'янма",
      Namibia: "Намібія",
      Nauru: "Науру",
      Nepal: "Непал",
      Netherlands: "Нідерланди",
      "New Caledonia": "Нова Каледонія",
      "New Zealand": "Нова Зеландія",
      Nicaragua: "Нікарагуа",
      Niger: "Нігер",
      Nigeria: "Нігерія",
      Niue: "Ніуе",
      "Norfolk Island": "Острів Норфолк",
      "North Korea": "Північна Корея",
      "North Macedonia": "Північна Македонія",
      "Northern Mariana Islands": "Північні Маріанські Острови",
      Norway: "Норвегія",
      Oman: "Оман",
      Pakistan: "Пакистан",
      Palau: "Палау",
      Palestine: "Палестинська держава",
      Panama: "Панама",
      "Papua New Guinea": "Папуа Нова Гвінея",
      Paraguay: "Парагвай",
      Peru: "Перу",
      Philippines: "Філіппіни",
      "Pitcairn Islands": "Острови Піткерн",
      Poland: "Польща",
      Portugal: "Португалія",
      "Puerto Rico": "Пуерто-Рико",
      Qatar: "Катар",
      "Republic of the Congo": "Демократична Республіка Конго",
      Romania: "Румунія",
      Russia: "Росія",
      Rwanda: "Руанда",
      Réunion: "Реюньйон",
      "Saint Barthélemy": "Сен-Бартельмі",
      "Saint Helena, Ascension and Tristan da Cunha":
        "Острови Святої Єлени, Вознесіння і Тристан-да-Кунья",
      "Saint Kitts and Nevis": "Сент-Кіттс і Невіс",
      "Saint Lucia": "Сент-Люсія",
      "Saint Martin": "Сен-Мартен (острів)",
      "Saint Pierre and Miquelon": "Сен-П'єр і Мікелон",
      "Saint Vincent and the Grenadines": "Сент-Вінсент і Гренадини",
      Samoa: "Самоа",
      "San Marino": "Сан-Марино",
      "Saudi Arabia": "Саудівська Аравія",
      Senegal: "Сенегал",
      Serbia: "Сербія",
      Seychelles: "Сейшельські Острови",
      "Sierra Leone": "Сьєрра-Леоне",
      Singapore: "Сінгапур",
      "Sint Maarten": "Сен-Мартен (Франція)",
      Slovakia: "Словаччина",
      Slovenia: "Словенія",
      "Solomon Islands": "Соломонові Острови",
      Somalia: "Сомалі",
      "South Africa": "Південно-Африканська Республіка",
      "South Georgia": "Південна Джорджія і Південні Сандвічеві Острови",
      "South Korea": "Південна Корея",
      "South Sudan": "Південний Судан",
      Spain: "Іспанія",
      "Sri Lanka": "Шрі-Ланка",
      Sudan: "Судан",
      Suriname: "Суринам",
      "Svalbard and Jan Mayen": "Свальбард",
      Sweden: "Швеція",
      Switzerland: "Швейцарія",
      Syria: "Сирія",
      "São Tomé and Príncipe": "Сан-Томе і Принсіпі",
      Taiwan: "Тайвань",
      Tajikistan: "Таджикистан",
      Tanzania: "Танзанія",
      Thailand: "Таїланд",
      "Timor-Leste": "Східний Тимор",
      Togo: "Того",
      Tokelau: "Токелау",
      Tonga: "Тонга",
      "Trinidad and Tobago": "Тринідад і Тобаго",
      Tunisia: "Туніс",
      Turkey: "Туреччина",
      Turkmenistan: "Туркменістан",
      "Turks and Caicos Islands": "Острови Теркс і Кайкос",
      Tuvalu: "Тувалу",
      Uganda: "Уганда",
      Ukraine: "Україна",
      "United Arab Emirates": "Об'єднані Арабські Емірати",
      "United Kingdom": "Велика Британія",
      "United States": "Сполучені Штати Америки",
      "United States Minor Outlying Islands": "Зовнішні малі острови США",
      "United States Virgin Islands": "Американські Віргінські Острови",
      Uruguay: "Уругвай",
      Uzbekistan: "Узбекистан",
      Vanuatu: "Вануату",
      "Vatican City": "Ватикан",
      Venezuela: "Венесуела",
      Vietnam: "В'єтнам",
      "Wallis and Futuna": "Волліс і Футуна",
      "Western Sahara": "Західна Сахара",
      Yemen: "Ємен",
      Zambia: "Замбія",
      Zimbabwe: "Зімбабве",
      "Aland Islands": "Аландські острови",
    },
    capitals: {
      Canberra: "Канберра",
      Vienna: "Відень",
      Baku: "Баку",
      Mariehamn: "Марієгамн",
      Tirana: "Тирана",
      Algiers: "Алжир",
      "Pago Pago": "Паго-Паго",
      "Charlotte Amalie": "Шарлотта-Амалія",
      "The Valley": "Валлі",
      Luanda: "Луанда",
      "Andorra la Vella": "Андорра-ла-Велья",
      "Saint John's": "Сент-Джонс",
      "Buenos Aires": "Буенос-Айрес",
      Oranjestad: "Ораньєстад",
      Kabul: "Кабул",
      Nassau: "Нассау",
      Dhaka: "Дакка",
      Bridgetown: "Бриджтаун",
      Manama: "Манама",
      Belmopan: "Бельмопан",
      Brussels: "Брюссель",
      "Porto-Novo": "Порто-Ново",
      Hamilton: "Гамільтон",
      Minsk: "Мінськ",
      Sofia: "Софія",
      Sucre: "Сукре",
      Sarajevo: "Сараєво",
      Gaborone: "Габороне",
      Brasília: "Бразилія",
      "Diego Garcia": "Дієго-Гарсія",
      "Road Town": "Род-Таун",
      "Bandar Seri Begawan": "Бандар-Сері-Бегаван",
      Ouagadougou: "Уагадугу",
      Gitega: "Гітега",
      Thimphu: "Тхімпху",
      Hanoi: "Ханой",
      "Port Vila": "Порт-Віла",
      "Vatican City": "Ватикан",
      London: "Лондон",
      Caracas: "Каракас",
      Yerevan: "Єреван",
      "Mata-Utu": "Мата-Уту",
      Libreville: "Лібревіль",
      "Port-au-Prince": "Порт-о-Пренс",
      Banjul: "Банжул",
      Accra: "Аккра",
      Georgetown: "Джорджтаун",
      "Basse-Terre": "Бас-Тер",
      "Guatemala City": "Гватемала",
      Conakry: "Конакрі",
      Bissau: "Бісау",
      "St. Peter Port": "Сент-Пітер-Порт",
      Gibraltar: "Гібралтар",
      Tegucigalpa: "Тегусігальпа",
      "City of Victoria": "Вікторія",
      "St. George's": "Сент-Джордж",
      Nuuk: "Нуук",
      Athens: "Афіни",
      Tbilisi: "Тбілісі",
      Hagåtña: "Хагатна",
      Copenhagen: "Копенгаген",
      Brazzaville: "Браззавіль",
      "Saint Helier": "Сент-Гелієр",
      Djibouti: "Джибуті",
      Roseau: "Розо",
      "Santo Domingo": "Санто-Домінго",
      Kinshasa: "Кіншаса",
      Quito: "Кіто",
      Malabo: "Малабо",
      Asmara: "Асмера",
      Mbabane: "Мбабане",
      Tallinn: "Таллінн",
      "Addis Ababa": "Аддис-Абеба",
      Cairo: "Каїр",
      "Sana'a": "Сана",
      Lusaka: "Лусака",
      "El Aaiún": "Ель-Аюн",
      Harare: "Хараре",
      "Washington DC": "Вашингтон",
      Jerusalem: "Єрусалим",
      "New Delhi": "Нью-Делі",
      Jakarta: "Джакарта",
      Baghdad: "Багдад",
      Tehran: "Тегеран",
      Dublin: "Дублін",
      Reykjavik: "Рейк'явік",
      Madrid: "Мадрид",
      Rome: "Рим",
      Amman: "Амман",
      Praia: "Прая",
      Astana: "Астана",
      "George Town": "Джорджтаун",
      "Phnom Penh": "Пномпень",
      Yaoundé: "Яунде",
      Ottawa: "Оттава",
      Kralendijk: "Кралендейк",
      Doha: "Доха",
      Nairobi: "Найробі",
      Bishkek: "Бішкек",
      Beijing: "Пекін",
      Nicosia: "Нікосія",
      "South Tarawa": "Південна Тарава",
      "West Island": "Вест-Айленд",
      Bogotá: "Богота",
      Moroni: "Мороні",
      Pristina: "Приштина",
      "San José": "Сан-Хосе",
      Yamoussoukro: "Ямусукро",
      Havana: "Гавана",
      "Kuwait City": "Ель-Кувейт",
      Willemstad: "Віллемстад",
      Vientiane: "В'єнтьян",
      Riga: "Рига",
      Maseru: "Масеру",
      Vilnius: "Вільнюс",
      Monrovia: "Монровія",
      Beirut: "Бейрут",
      Tripoli: "Тріполі",
      Vaduz: "Вадуц",
      Luxembourg: "Люксембург",
      Naypyidaw: "Найп'їдо",
      "Port Louis": "Порт-Луї",
      Nouakchott: "Нуакшот",
      Antananarivo: "Антананаріву",
      Mamoudzou: "Мамудзу",
      Lilongwe: "Лілонгве",
      "Kuala Lumpur": "Куала-Лумпур",
      Bamako: "Бамако",
      Malé: "Мале",
      Valletta: "Валлетта",
      Rabat: "Рабат",
      "Fort-de-France": "Фор-де-Франс",
      Majuro: "Маджуро",
      "Mexico City": "Мехіко",
      Maputo: "Мапуту",
      Chișinău: "Кишинів",
      Monaco: "Монако",
      "Ulan Bator": "Улан-Батор",
      Plymouth: "Плімут",
      Windhoek: "Віндгук",
      Yaren: "Ярен",
      Kathmandu: "Катманду",
      Niamey: "Ніамей",
      Abuja: "Абуджа",
      Amsterdam: "Амстердам",
      Managua: "Манагуа",
      Berlin: "Берлін",
      Alofi: "Алофі",
      Wellington: "Веллінгтон",
      Nouméa: "Нумеа",
      Oslo: "Осло",
      "Abu Dhabi": "Абу-Дабі",
      Muscat: "Маскат",
      Douglas: "Дуглас",
      Kingston: "Кінгстон",
      "Flying Fish Cove": "Флаїнг-Фіш-Коув",
      Avarua: "Аваруа",
      Adamstown: "Адамстаун",
      Jamestown: "Джеймстаун",
      "Cockburn Town": "Коберн-Таун",
      Islamabad: "Ісламабад",
      Ngerulmud: "Нгерулмуд",
      Ramallah: "Рамалла",
      "Panama City": "Панама",
      "Port Moresby": "Порт-Морсбі",
      Asunción: "Асунсьйон",
      Lima: "Ліма",
      "King Edward Point": "Кінг-Едвард-Пойнт",
      Seoul: "Сеул",
      Juba: "Джуба",
      Pretoria: "Преторія",
      Pyongyang: "Пхеньян",
      Skopje: "Скоп'є",
      Saipan: "Сайпан",
      Warsaw: "Варшава",
      Lisbon: "Лісабон",
      "San Juan": "Сан-Хуан",
      "Saint-Denis": "Сен-Дені",
      Moscow: "Москва",
      Kigali: "Кігалі",
      Bucharest: "Бухарест",
      "San Salvador": "Сан-Сальвадор",
      Apia: "Апіа",
      "City of San Marino": "Сан-Марино",
      "São Tomé": "Сан-Томе",
      Riyadh: "Ер-Ріяд",
      Longyearbyen: "Лонг'їр",
      Victoria: "Вікторія",
      Gustavia: "Густавія",
      Marigot: "Маріго ",
      Philipsburg: "Філіпсбург",
      "Saint-Pierre": "Сен-П'єр",
      Dakar: "Дакар",
      Kingstown: "Кінгстаун",
      Basseterre: "Бастер",
      Castries: "Кастрі",
      Belgrade: "Белград",
      Damascus: "Дамаск",
      Singapore: "Сінгапур",
      Bratislava: "Братислава",
      Ljubljana: "Любляна",
      Honiara: "Хоніара",
      Mogadishu: "Могадішо",
      "Washington, D.C.": "Вашингтон",
      Khartoum: "Хартум",
      Paramaribo: "Парамарибо",
      Dili: "Ділі",
      Freetown: "Фрітаун",
      Dushanbe: "Душанбе",
      Bangkok: "Бангкок",
      Taipei: "Тайбей",
      Dodoma: "Додома",
      Lomé: "Ломе",
      Fakaofo: "Факаофо",
      "Nuku'alofa": "Нукуалофа",
      "Port of Spain": "Порт-оф-Спейн",
      Funafuti: "Фунафуті",
      Tunis: "Туніс",
      Ankara: "Анкара",
      Ashgabat: "Ашгабат",
      Kampala: "Кампала",
      Budapest: "Будапешт",
      Tashkent: "Ташкент",
      Kyiv: "Київ",
      Montevideo: "Монтевідео",
      Tórshavn: "Торсгавн",
      Palikir: "Палікір",
      Suva: "Сува",
      Manila: "Маніла",
      Helsinki: "Гельсінкі",
      Stanley: "Порт-Стенлі",
      Paris: "Париж",
      Cayenne: "Каєнна",
      Papeetē: "Папеете",
      "Port-aux-Français": "Порт-о-Франсе",
      Zagreb: "Загреб",
      Bangui: "Бангі",
      "N'Djamena": "Нджамена",
      Prague: "Прага",
      Santiago: "Сантьяго",
      Podgorica: "Подгориця",
      Bern: "Берн",
      Stockholm: "Стокгольм",
      "Sri Jayawardenepura Kotte": "Коломбо",
      Tokyo: "Токіо",
    },
    of: "з",
    SCORE: "РАХУНОК: ",
    "Guess Flag": "Вгадай Прапор:",
    "RETURN TO MAP": "ПОВЕРНУТИСЯ НА МАПУ",
    "START AGAIN": "ПОЧАТИ ЗНОВУ",
    "NEXT QUESTION": "НАСТУПНЕ ПИТАННЯ",
    "FINISH QUIZ": "ЗАКІНЧИТИ ВІКТОРИНУ",
    "Are you sure you want to leave this quiz? Current quiz data will not be saved!":
      "Ви впевнені, що бажаєте залишити цей тест? Поточні дані вікторини не будуть збережені!",
    "Only Independent Countries": "Тільки незалежні країни",
    "All Countries": "Всі країни",
    "Guess Flag By Country Name Quiz":
      "Вікторина Вгадай Прапор За Назвою Країни",
    "Guess Country Name By Flag Quiz":
      "Вікторина Вгадай Назву Країни За Прапором",
    "Guess Country Capital By Flag Quiz":
      "Вікторина Вгадай Столицю Країни За Прапором",
    "Guess Flag By Country Capital Quiz":
      "Вікторина Вгадай Прапор За Столицею Країни",
    "Guess Country Name By Capital Quiz":
      "Вікторина Вгадай Назву Країни За Столицею Країни",
    "Guess Capital By Country Name Quiz":
      "Вікторина Вгадай Столицю За Назвою Країни",
    "Guess Country On Map Quiz": "Вікторина Знайди Країну На Мапі",
    "War Aggressor": "Країна Агресор",
    "Aggressor Supporter": "Прибічник Агресора",
    "Flag By Country Name Quiz": "Вікторина Прапор За Назвою Країни",
    "Country Name By Flag Quiz": "Вікторина Назва Країни За Прапором",
    "Country Capital By Flag Quiz": "Вікторина Столиця Країни За Прапором",
    "Flag By Country Capital Quiz": "Вікторина Прапор За Столицею Країни",
    "Country Name By Capital Quiz": "Вікторина Назва Країни За Столицею Країни",
    "Capital By Country Name Quiz": "Вікторина Столиця Країни За Назвою Країни",
    "Country On Map Quiz": "Вікторина Країна На Мапі",
    "About Project": "Про Проект",
    Correct: "Вірно",
    Incorrect: "Невірно",
    MENU: "МЕНЮ",
    "Slavutych, Ukraine - birthplace of the project":
      "Славутич, Україна - місце народження проекту",
    "World Countries And Quizzes": "Світові Країни Та Вікторини",
    "project which is developed for learning Geography and World Countries.":
      "це проект, який розроблений для вивчення Географії та Країн Світу.",
    "Here you can find all countries of the world on a map, brief information about selected countries, links to Wikipedia pages of a specific country. It is also possible to take various quizzes.":
      "Тут ви можете знайти всі країни світу на мапі, коротку інформацію про обрані країни, посилання на сторінки Вікіпедії певної країни. Також є можливість пройти різні вікторини.",
    "Guess the country's flag from the suggested country name. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Відгадайте прапор країни за запропонованою назвою країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 100 балів.",
    "Guess the country's name from the suggested country flag image. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Відгадайте назву країни за запропонованим зображенням прапора країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 100 балів.",
    "Guess the country's capital from the suggested country flag image. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Відгадайте столицю країни за запропонованим зображенням прапора країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 100 балів.",
    "Guess the country's flag from the suggested country's capital. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Відгадайте прапор країни за запропонованою столицею країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 100 балів.",
    "Guess the country's name from the suggested country capital. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Відгадайте назву країни за запропонованою столицею країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 100 балів.",
    "Guess the country's capital from the suggested country name. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Відгадайте столицю країни за запропонованою назвою країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 100 балів.",
    "Guess the country on the map from the suggested country name. The quiz contains 35 questions. Get 300 points for each correct answer.":
      "Відгадайте розташування країни на світовій мапі за запропонованою назвою країни. Вікторина містить 35 питань. За кожну правильну відповідь отримуйте 300 балів.",
    "Project was created by Software Developer from Ukraine -":
      "Проект створений програмістом з України -",
    "You can support Ukraine in the fight against Russia's military aggression:":
      "Ви можете підтримати Україну в боротьбі з військовою агресією Росії:",
    "Quizzes:": "Вікторини:",
    "Dmytro Solovei": "Дмитро Соловей",
    "You can reach me by e-mail:":
      "Ви можете зв'язатися зі мною електронною поштою:",
    "Come Back Alive": "Повернись Живим",
    "All Countries": "Всі Країни",
    "Search Or Select Counties...": "Пошук або вибір країни...",
    Selected: "Вибрані",
    "World Map": "Світова Мапа",
    "Used Map Library:": "Використана бібліотека мап:",
    Finished: "Закінчено",
    Countries: "Країни",
    "Quiz Result": "Результат Вікторини",
    Points: "Балів",
    "Correct answers out of": "Правильні відповіді з",
    Close: "Закрити",
    Wikipedia: "Вікіпедія",
    Reset: "Скинути",
    Sort: "Сортувати:",
    Up: "Вгору:",
    Down: "Вниз:",
    Capital: "Столиця",
    Region: "Частина світу",
    Subregion: "Регіон",
    Area: "Площа",
    Population: "Населення",
    "square km": "квадратних км",
    people: "осіб",
    Europe: "Європа",
    Americas: "Америка",
    Oceania: "Океанія",
    Africa: "Африка",
    Asia: "Азія",
    Antarctic: "Антарктика",
    "Eastern Europe": "Східна Європа",
    "North America": "Північна Америка",
    "Eastern Africa": "Східна Африка",
    Micronesia: "Мікронезія",
    "South America": "Південна Америка",
    "Western Africa": "Західна Африка",
    "Middle Africa": "Середня Африка",
    "Southeast Europe": "Південно-Східна Європа",
    Caribbean: "Карибський басейн",
    Polynesia: "Полінезія",
    "Western Asia": "Західна Азія",
    "South-Eastern Asia": "Південно-Східна Азія",
    "Northern Europe": "Північна Європа",
    "Northern Africa": "Північна Африка",
    "Southern Europe": "Південна Європа",
    "Southern Asia": "Південна Азія",
    "Southern Africa": "Південна Африка",
    "Central America": "Центральна Америка",
    "Central Europe": "Центральна Європа",
    Melanesia: "Меланезія",
    "Central Asia": "Центральна Азія",
    "Australia and New Zealand": "Австралія та Нова Зеландія",
    "Western Europe": "Західна Європа",
    "Eastern Asia": "Східна Азія",
  },
  en: {
    countries: {
      Afghanistan: "Afghanistan",
      Albania: "Albania",
      Algeria: "Algeria",
      "American Samoa": "American Samoa",
      Andorra: "Andorra",
      Angola: "Angola",
      Anguilla: "Anguilla",
      Antarctica: "Antarctica",
      "Antigua and Barbuda": "Antigua and Barbuda",
      Argentina: "Argentina",
      Armenia: "Armenia",
      Aruba: "Aruba",
      Australia: "Australia",
      Austria: "Austria",
      Azerbaijan: "Azerbaijan",
      Bahamas: "Bahamas",
      Bahrain: "Bahrain",
      Bangladesh: "Bangladesh",
      Barbados: "Barbados",
      Belarus: "Belarus",
      Belgium: "Belgium",
      Belize: "Belize",
      Benin: "Benin",
      Bermuda: "Bermuda",
      Bhutan: "Bhutan",
      Bolivia: "Bolivia",
      "Bosnia and Herzegovina": "Bosnia and Herzegovina",
      Botswana: "Botswana",
      "Bouvet Island": "Bouvet Island",
      Brazil: "Brazil",
      "British Indian Ocean Territory": "British Indian Ocean Territory",
      "British Virgin Islands": "British Virgin Islands",
      Brunei: "Brunei",
      Bulgaria: "Bulgaria",
      "Burkina Faso": "Burkina Faso",
      Burundi: "Burundi",
      Cambodia: "Cambodia",
      Cameroon: "Cameroon",
      Canada: "Canada",
      "Cape Verde": "Cape Verde",
      "Caribbean Netherlands": "Caribbean Netherlands",
      "Cayman Islands": "Cayman Islands",
      "Central African Republic": "Central African Republic",
      Chad: "Chad",
      Chile: "Chile",
      China: "China",
      "Christmas Island": "Christmas Island",
      "Cocos (Keeling) Islands": "Cocos (Keeling) Islands",
      Colombia: "Colombia",
      Comoros: "Comoros",
      "Cook Islands": "Cook Islands",
      "Costa Rica": "Costa Rica",
      Croatia: "Croatia",
      Cuba: "Cuba",
      Curaçao: "Curaçao",
      Cyprus: "Cyprus",
      Czechia: "Czechia",
      "DR Congo": "DR Congo",
      Denmark: "Denmark",
      Djibouti: "Djibouti",
      Dominica: "Dominica",
      "Dominican Republic": "Dominican Republic",
      Ecuador: "Ecuador",
      Egypt: "Egypt",
      "El Salvador": "El Salvador",
      "Equatorial Guinea": "Equatorial Guinea",
      Eritrea: "Eritrea",
      Estonia: "Estonia",
      Eswatini: "Eswatini",
      Ethiopia: "Ethiopia",
      "Falkland Islands": "Falkland Islands",
      "Faroe Islands": "Faroe Islands",
      Fiji: "Fiji",
      Finland: "Finland",
      France: "France",
      "French Guiana": "French Guiana",
      "French Polynesia": "French Polynesia",
      "French Southern and Antarctic Lands":
        "French Southern and Antarctic Lands",
      Gabon: "Gabon",
      Gambia: "Gambia",
      Georgia: "Georgia",
      Germany: "Germany",
      Ghana: "Ghana",
      Gibraltar: "Gibraltar",
      Greece: "Greece",
      Greenland: "Greenland",
      Grenada: "Grenada",
      Guadeloupe: "Guadeloupe",
      Guam: "Guam",
      Guatemala: "Guatemala",
      Guernsey: "Guernsey",
      Guinea: "Guinea",
      "Guinea-Bissau": "Guinea-Bissau",
      Guyana: "Guyana",
      Haiti: "Haiti",
      "Heard Island and McDonald Islands": "Heard Island and McDonald Islands",
      Honduras: "Honduras",
      "Hong Kong": "Hong Kong",
      Hungary: "Hungary",
      Iceland: "Iceland",
      India: "India",
      Indonesia: "Indonesia",
      Iran: "Iran",
      Iraq: "Iraq",
      Ireland: "Ireland",
      "Isle of Man": "Isle of Man",
      Israel: "Israel",
      Italy: "Italy",
      "Ivory Coast": "Ivory Coast",
      Jamaica: "Jamaica",
      Japan: "Japan",
      Jersey: "Jersey",
      Jordan: "Jordan",
      Kazakhstan: "Kazakhstan",
      Kenya: "Kenya",
      Kiribati: "Kiribati",
      Kosovo: "Kosovo",
      Kuwait: "Kuwait",
      Kyrgyzstan: "Kyrgyzstan",
      Laos: "Laos",
      Latvia: "Latvia",
      Lebanon: "Lebanon",
      Lesotho: "Lesotho",
      Liberia: "Liberia",
      Libya: "Libya",
      Liechtenstein: "Liechtenstein",
      Lithuania: "Lithuania",
      Luxembourg: "Luxembourg",
      Macau: "Macau",
      Madagascar: "Madagascar",
      Malawi: "Malawi",
      Malaysia: "Malaysia",
      Maldives: "Maldives",
      Mali: "Mali",
      Malta: "Malta",
      "Marshall Islands": "Marshall Islands",
      Martinique: "Martinique",
      Mauritania: "Mauritania",
      Mauritius: "Mauritius",
      Mayotte: "Mayotte",
      Mexico: "Mexico",
      Micronesia: "Federated States of Micronesia",
      Moldova: "Moldova",
      Monaco: "Monaco",
      Mongolia: "Mongolia",
      Montenegro: "Montenegro",
      Montserrat: "Montserrat",
      Morocco: "Morocco",
      Mozambique: "Mozambique",
      Myanmar: "Myanmar",
      Namibia: "Namibia",
      Nauru: "Nauru",
      Nepal: "Nepal",
      Netherlands: "Netherlands",
      "New Caledonia": "New Caledonia",
      "New Zealand": "New Zealand",
      Nicaragua: "Nicaragua",
      Niger: "Niger",
      Nigeria: "Nigeria",
      Niue: "Niue",
      "Norfolk Island": "Norfolk Island",
      "North Korea": "North Korea",
      "North Macedonia": "North Macedonia",
      "Northern Mariana Islands": "Northern Mariana Islands",
      Norway: "Norway",
      Oman: "Oman",
      Pakistan: "Pakistan",
      Palau: "Palau",
      Palestine: "Palestine",
      Panama: "Panama",
      "Papua New Guinea": "Papua New Guinea",
      Paraguay: "Paraguay",
      Peru: "Peru",
      Philippines: "Philippines",
      "Pitcairn Islands": "Pitcairn Islands",
      Poland: "Poland",
      Portugal: "Portugal",
      "Puerto Rico": "Puerto Rico",
      Qatar: "Qatar",
      "Republic of the Congo": "Republic of the Congo",
      Romania: "Romania",
      Russia: "Russia",
      Rwanda: "Rwanda",
      Réunion: "Réunion",
      "Saint Barthélemy": "Saint Barthélemy",
      "Saint Helena, Ascension and Tristan da Cunha":
        "Saint Helena, Ascension and Tristan da Cunha",
      "Saint Kitts and Nevis": "Saint Kitts and Nevis",
      "Saint Lucia": "Saint Lucia",
      "Saint Martin": "Saint Martin (island)",
      "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
      Samoa: "Samoa",
      "San Marino": "San Marino",
      "Saudi Arabia": "Saudi Arabia",
      Senegal: "Senegal",
      Serbia: "Serbia",
      Seychelles: "Seychelles",
      "Sierra Leone": "Sierra Leone",
      Singapore: "Singapore",
      "Sint Maarten": "Sint Maarten",
      Slovakia: "Slovakia",
      Slovenia: "Slovenia",
      "Solomon Islands": "Solomon Islands",
      Somalia: "Somalia",
      "South Africa": "South Africa",
      "South Georgia": "South Georgia",
      "South Korea": "South Korea",
      "South Sudan": "South Sudan",
      Spain: "Spain",
      "Sri Lanka": "Sri Lanka",
      Sudan: "Sudan",
      Suriname: "Suriname",
      "Svalbard and Jan Mayen": "Svalbard and Jan Mayen",
      Sweden: "Sweden",
      Switzerland: "Switzerland",
      Syria: "Syria",
      "São Tomé and Príncipe": "São Tomé and Príncipe",
      Taiwan: "Taiwan",
      Tajikistan: "Tajikistan",
      Tanzania: "Tanzania",
      Thailand: "Thailand",
      "Timor-Leste": "Timor-Leste",
      Togo: "Togo",
      Tokelau: "Tokelau",
      Tonga: "Tonga",
      "Trinidad and Tobago": "Trinidad and Tobago",
      Tunisia: "Tunisia",
      Turkey: "Turkey",
      Turkmenistan: "Turkmenistan",
      "Turks and Caicos Islands": "Turks and Caicos Islands",
      Tuvalu: "Tuvalu",
      Uganda: "Uganda",
      Ukraine: "Ukraine",
      "United Arab Emirates": "United Arab Emirates",
      "United Kingdom": "United Kingdom",
      "United States": "United States",
      "United States Minor Outlying Islands":
        "United States Minor Outlying Islands",
      "United States Virgin Islands": "United States Virgin Islands",
      Uruguay: "Uruguay",
      Uzbekistan: "Uzbekistan",
      Vanuatu: "Vanuatu",
      "Vatican City": "Vatican City",
      Venezuela: "Venezuela",
      Vietnam: "Vietnam",
      "Wallis and Futuna": "Wallis and Futuna",
      "Western Sahara": "Western Sahara",
      Yemen: "Yemen",
      Zambia: "Zambia",
      Zimbabwe: "Zimbabwe",
      "Aland Islands": "Aland Islands",
    },
    capitals: {
      Canberra: "Canberra",
      Vienna: "Vienna",
      Baku: "Baku",
      Mariehamn: "Mariehamn",
      Tirana: "Tirana",
      Algiers: "Algiers",
      "Pago Pago": "Pago Pago",
      "Charlotte Amalie": "Charlotte Amalie",
      "The Valley": "The Valley",
      Luanda: "Luanda",
      "Andorra la Vella": "Andorra la Vella",
      "Saint John's": "Saint John's",
      "Buenos Aires": "Buenos Aires",
      Oranjestad: "Oranjestad",
      Kabul: "Kabul",
      Nassau: "Nassau",
      Dhaka: "Dhaka",
      Bridgetown: "Bridgetown",
      Manama: "Manama",
      Belmopan: "Belmopan",
      Brussels: "Brussels",
      "Porto-Novo": "Porto-Novo",
      Hamilton: "Hamilton",
      Minsk: "Minsk",
      Sofia: "Sofia",
      Sucre: "Sucre",
      Sarajevo: "Sarajevo",
      Gaborone: "Gaborone",
      Brasília: "Brasília",
      "Diego Garcia": "Diego Garcia",
      "Road Town": "Road Town",
      "Bandar Seri Begawan": "Bandar Seri Begawan",
      Ouagadougou: "Ouagadougou",
      Gitega: "Gitega",
      Thimphu: "Thimphu",
      Hanoi: "Hanoi",
      "Port Vila": "Port Vila",
      "Vatican City": "Vatican City",
      London: "London",
      Caracas: "Caracas",
      Yerevan: "Yerevan",
      "Mata-Utu": "Mata-Utu",
      Libreville: "Libreville",
      "Port-au-Prince": "Port-au-Prince",
      Banjul: "Banjul",
      Accra: "Accra",
      Georgetown: "Georgetown",
      "Basse-Terre": "Basse-Terre",
      "Guatemala City": "Guatemala City",
      Conakry: "Conakry",
      Bissau: "Bissau",
      "St. Peter Port": "St. Peter Port",
      Gibraltar: "Gibraltar",
      Tegucigalpa: "Tegucigalpa",
      "City of Victoria": "City of Victoria",
      "St. George's": "St. George's",
      Nuuk: "Nuuk",
      Athens: "Athens",
      Tbilisi: "Tbilisi",
      Hagåtña: "Hagåtña",
      Copenhagen: "Copenhagen",
      Brazzaville: "Brazzaville",
      "Saint Helier": "Saint Helier",
      Djibouti: "Djibouti",
      Roseau: "Roseau",
      "Santo Domingo": "Santo Domingo",
      Kinshasa: "Kinshasa",
      Quito: "Quito",
      Malabo: "Malabo",
      Asmara: "Asmara",
      Mbabane: "Mbabane",
      Tallinn: "Tallinn",
      "Addis Ababa": "Addis Ababa",
      Cairo: "Cairo",
      "Sana'a": "Sana'a",
      Lusaka: "Lusaka",
      "El Aaiún": "El Aaiún",
      Harare: "Harare",
      "Washington DC": "Washington DC",
      Jerusalem: "Jerusalem",
      "New Delhi": "New Delhi",
      Jakarta: "Jakarta",
      Baghdad: "Baghdad",
      Tehran: "Tehran",
      Dublin: "Dublin",
      Reykjavik: "Reykjavik",
      Madrid: "Madrid",
      Rome: "Rome",
      Amman: "Amman",
      Praia: "Praia",
      Astana: "Astana",
      "George Town": "George Town",
      "Phnom Penh": "Phnom Penh",
      Yaoundé: "Yaoundé",
      Ottawa: "Ottawa",
      Kralendijk: "Kralendijk",
      Doha: "Doha",
      Nairobi: "Nairobi",
      Bishkek: "Bishkek",
      Beijing: "Beijing",
      Nicosia: "Nicosia",
      "South Tarawa": "South Tarawa",
      "West Island": "West Island",
      Bogotá: "Bogotá",
      Moroni: "Moroni",
      Pristina: "Pristina",
      "San José": "San José",
      Yamoussoukro: "Yamoussoukro",
      Havana: "Havana",
      "Kuwait City": "Kuwait City",
      Willemstad: "Willemstad",
      Vientiane: "Vientiane",
      Riga: "Riga",
      Maseru: "Maseru",
      Vilnius: "Vilnius",
      Monrovia: "Monrovia",
      Beirut: "Beirut",
      Tripoli: "Tripoli",
      Vaduz: "Vaduz",
      Luxembourg: "Luxembourg",
      Naypyidaw: "Naypyidaw",
      "Port Louis": "Port Louis",
      Nouakchott: "Nouakchott",
      Antananarivo: "Antananarivo",
      Mamoudzou: "Mamoudzou",
      Lilongwe: "Lilongwe",
      "Kuala Lumpur": "Kuala Lumpur",
      Bamako: "Bamako",
      Malé: "Malé",
      Valletta: "Valletta",
      Rabat: "Rabat",
      "Fort-de-France": "Fort-de-France",
      Majuro: "Majuro",
      "Mexico City": "Mexico City",
      Maputo: "Maputo",
      Chișinău: "Chișinău",
      Monaco: "Monaco",
      "Ulan Bator": "Ulan Bator",
      Plymouth: "Plymouth",
      Windhoek: "Windhoek",
      Yaren: "Yaren",
      Kathmandu: "Kathmandu",
      Niamey: "Niamey",
      Abuja: "Abuja",
      Amsterdam: "Amsterdam",
      Managua: "Managua",
      Berlin: "Berlin",
      Alofi: "Alofi",
      Wellington: "Wellington",
      Nouméa: "Nouméa",
      Oslo: "Oslo",
      "Abu Dhabi": "Abu Dhabi",
      Muscat: "Muscat",
      Douglas: "Douglas",
      Kingston: "Kingston",
      "Flying Fish Cove": "Flying Fish Cove",
      Avarua: "Avarua",
      Adamstown: "Adamstown",
      Jamestown: "Jamestown",
      "Cockburn Town": "Cockburn Town",
      Islamabad: "Islamabad",
      Ngerulmud: "Ngerulmud",
      Ramallah: "Ramallah",
      "Panama City": "Panama City",
      "Port Moresby": "Port Moresby",
      Asunción: "Asunción",
      Lima: "Lima",
      "King Edward Point": "King Edward Point",
      Seoul: "Seoul",
      Juba: "Juba",
      Pretoria: "Pretoria",
      Pyongyang: "Pyongyang",
      Skopje: "Skopje",
      Saipan: "Saipan",
      Warsaw: "Warsaw",
      Lisbon: "Lisbon",
      "San Juan": "San Juan",
      "Saint-Denis": "Saint-Denis",
      Moscow: "Moscow",
      Kigali: "Kigali",
      Bucharest: "Bucharest",
      "San Salvador": "San Salvador",
      Apia: "Apia",
      "City of San Marino": "City of San Marino",
      "São Tomé": "São Tomé",
      Riyadh: "Riyadh",
      Longyearbyen: "Longyearbyen",
      Victoria: "Victoria",
      Gustavia: "Gustavia",
      Marigot: "Marigot",
      Philipsburg: "Philipsburg",
      "Saint-Pierre": "Saint-Pierre",
      Dakar: "Dakar",
      Kingstown: "Kingstown",
      Basseterre: "Basseterre",
      Castries: "Castries",
      Belgrade: "Belgrade",
      Damascus: "Damascus",
      Singapore: "Singapore",
      Bratislava: "Bratislava",
      Ljubljana: "Ljubljana",
      Honiara: "Honiara",
      Mogadishu: "Mogadishu",
      "Washington, D.C.": "Washington, D.C.",
      Khartoum: "Khartoum",
      Paramaribo: "Paramaribo",
      Dili: "Dili",
      Freetown: "Freetown",
      Dushanbe: "Dushanbe",
      Bangkok: "Bangkok",
      Taipei: "Taipei",
      Dodoma: "Dodoma",
      Lomé: "Lomé",
      Fakaofo: "Fakaofo",
      "Nuku'alofa": "Nuku'alofa",
      "Port of Spain": "Port of Spain",
      Funafuti: "Funafuti",
      Tunis: "Tunis",
      Ankara: "Ankara",
      Ashgabat: "Ashgabat",
      Kampala: "Kampala",
      Budapest: "Budapest",
      Tashkent: "Tashkent",
      Kyiv: "Kyiv",
      Montevideo: "Montevideo",
      Tórshavn: "Tórshavn",
      Palikir: "Palikir",
      Suva: "Suva",
      Manila: "Manila",
      Helsinki: "Helsinki",
      Stanley: "Stanley",
      Paris: "Paris",
      Cayenne: "Cayenne",
      Papeetē: "Papeetē",
      "Port-aux-Français": "Port-aux-Français",
      Zagreb: "Zagreb",
      Bangui: "Bangui",
      "N'Djamena": "N'Djamena",
      Prague: "Prague",
      Santiago: "Santiago",
      Podgorica: "Podgorica",
      Bern: "Bern",
      Stockholm: "Stockholm",
      "Sri Jayawardenepura Kotte": "Sri Jayawardenepura Kotte",
      Tokyo: "Tokyo",
    },
    Points: "Points",
    SCORE: "SCORE:",
    of: "of",
    "Guess Flag": "Guess Flag:",
    "RETURN TO MAP": "RETURN TO MAP",
    "START AGAIN": "START AGAIN",
    "Guess Flag By Country Name Quiz": "Guess Flag By Country Name Quiz",
    "Guess Country Name By Flag Quiz": "Guess Country Name By Flag Quiz",
    "Guess Country Capital By Flag Quiz": "Guess Country Capital By Flag Quiz",
    "Guess Flag By Country Capital Quiz": "Guess Flag By Country Capital Quiz",
    "Guess Country Name By Capital Quiz": "Guess Country Name By Capital Quiz",
    "Guess Capital By Country Name Quiz": "Guess Capital By Country Name Quiz",
    "Are you sure you want to leave this quiz? Current quiz data will not be saved!":
      "Are you sure you want to leave this quiz? Current quiz data will not be saved!",
    "Only Independent Countries": "Only Independent Countries",
    "All Countries": "All Countries",
    "NEXT QUESTION": "NEXT QUESTION",
    "FINISH QUIZ": "FINISH QUIZ",
    "Flag By Country Name Quiz": "Flag By Country Name Quiz",
    "Country On Map Quiz": "Country On Map Quiz",
    "Guess Country On Map Quiz": "Guess Country On Map Quiz",
    "All Countries": "All Countries",
    "Search Or Select Counties...": "Search Or Select Counties...",
    Selected: "Selected",
    "War Aggressor": "War Aggressor",
    "Aggressor Supporter": "Aggressor Supporter",
    "About Project": "About Project",
    "World Countries And Quizzes": "World Countries And Quizzes",
    "project which is developed for learning Geography and World Countries.":
      "project which is developed for learning Geography and World Countries.",
    "Here you can find all countries of the world on a map, brief information about selected countries, links to Wikipedia pages of a specific country. It is also possible to take various quizzes.":
      "Here you can find all countries of the world on a map, brief information about selected countries, links to Wikipedia pages of a specific country. It is also possible to take various quizzes.",
    "Guess the country's flag from the suggested country name. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Guess the country's flag from the suggested country name. The quiz contains 35 questions. Get 100 points for each correct answer.",
    "Guess the country's name from the suggested country flag image. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Guess the country's name from the suggested country flag image. The quiz contains 35 questions. Get 100 points for each correct answer.",
    "Guess the country's capital from the suggested country flag image. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Guess the country's capital from the suggested country flag image. The quiz contains 35 questions. Get 100 points for each correct answer.",
    "Guess the country's flag from the suggested country's capital. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Guess the country's flag from the suggested country's capital. The quiz contains 35 questions. Get 100 points for each correct answer.",
    "Guess the country's name from the suggested country capital. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Guess the country's name from the suggested country capital. The quiz contains 35 questions. Get 100 points for each correct answer.",
    "Guess the country's capital from the suggested country name. The quiz contains 35 questions. Get 100 points for each correct answer.":
      "Guess the country's capital from the suggested country name. The quiz contains 35 questions. Get 100 points for each correct answer.",
    "Guess the country on the map from the suggested country name. The quiz contains 35 questions. Get 300 points for each correct answer.":
      "Guess the country on the map from the suggested country name. The quiz contains 35 questions. Get 300 points for each correct answer.",
    "Project was created by Software Developer from Ukraine -":
      "Project was created by Software Developer from Ukraine -",
    "You can support Ukraine in the fight against Russia's military aggression:":
      "You can support Ukraine in the fight against Russia's military aggression:",
    "Dmytro Solovei": "Dmytro Solovei",
    "You can reach me by e-mail:": "You can reach me by e-mail:",
    "Country Name By Flag Quiz": "Country Name By Flag Quiz",
    "Country Capital By Flag Quiz": "Country Capital By Flag Quiz",
    "Flag By Country Capital Quiz": "Flag By Country Capital Quiz",
    "Country Name By Capital Quiz": "Country Name By Capital Quiz",
    "Capital By Country Name Quiz": "Capital By Country Name Quiz",
    "Come Back Alive": "Come Back Alive",
    "Slavutych, Ukraine - birthplace of the project":
      "Slavutych, Ukraine - birthplace of the project",
    "Quizzes:": "Quizzes:",
    Correct: "Correct",
    "Quiz Result": "Quiz Result",
    "Correct answers out of": "Correct answers out of",
    Close: "Close",
    MENU: "MENU",
    Incorrect: "Incorrect",
    "World Map": "World Map",
    "Used Map Library:": "Used Map Library:",
    Finished: "Finished",
    Countries: "Countries",
    Wikipedia: "Wikipedia",
    Reset: "Reset",
    Sort: "Sort:",
    Up: "Up:",
    Down: "Down:",
    Capital: "Capital",
    Region: "Region",
    Subregion: "Subregion",
    Area: "Area",
    Population: "Population",
    "square km": "square km",
    people: "people",
    Europe: "Europe",
    Americas: "Americas",
    Oceania: "Oceania",
    Africa: "Africa",
    Asia: "Asia",
    Antarctic: "Antarctic",
    "Eastern Europe": "Eastern Europe",
    "North America": "North America",
    "Eastern Africa": "Eastern Africa",
    Micronesia: "Micronesia",
    "South America": "South America",
    "Western Africa": "Western Africa",
    "Middle Africa": "Middle Africa",
    "Southeast Europe": "Southeast Europe",
    Caribbean: "Caribbean",
    Polynesia: "Polynesia",
    "Western Asia": "Western Asia",
    "South-Eastern Asia": "South-Eastern Asia",
    "Northern Europe": "Northern Europe",
    "Northern Africa": "Northern Africa",
    "Southern Europe": "Southern Europe",
    "Southern Asia": "Southern Asia",
    "Southern Africa": "Southern Africa",
    "Central America": "Central America",
    "Central Europe": "Central Europe",
    Melanesia: "Melanesia",
    "Central Asia": "Central Asia",
    "Australia and New Zealand": "Australia and New Zealand",
    "Western Europe": "Western Europe",
    "Eastern Asia": "Eastern Asia",
  },
};
